### ISSUE TITLE
SSLException: Received fatal alert: protocol_version when mvnw downloads Maven ZIP

### ISSUE THREAD

**Issue by ppalaga** [srcdeps/srcdeps-core#32]
E.g. in this build: https://ci.appveyor.com/project/ppalaga/srcdeps-core/build/1.0.204

```.\mvnw.cmd clean install -B -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.3/apache-maven-3.5.3-bin.zip
Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Command exited with code 1
echo "failed"
"failed"
type srcdeps-maven-local-repository\target\test-projects\SrcdepsLocalRepositoryManagerTest_mvnGitBranch[3.3.1]_mvnGitBranch\log.txt
The system cannot find the path specified.
Command exited with code 1
```

**Comment by ppalaga** [comment]
This happens because AppVeyor provides Java 7 older than 1.7.0_131-b31 [1]

Adding -Dhttps.protocols=TLSv1.1,TLSv1.2  to `mvnw.cmd` and `mvnw` solves the problem inside Maven Wrapper, but uncovers other similar problems in Gradle when running `GradleBuildServiceTest`.

Rather than fixing all those, it is time to drop the support for Java 7.

[1] https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/?__hstc=31049440.83c81c201b59c8a6c302ede1e8d9429d.1534668348022.1534668348022.1534668348022.1&__hssc=31049440.1.1534668348024&__hsfp=1954947181
